version: "3"

networks:
  default:
    attachable: true

services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "${INFLUXDB_DB_PORT}:${INFLUXDB_DB_PORT}"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}"
      - "INFLUXDB_DB=speedtest"

  grafana:
    restart: always
    image: grafana/grafana:6.7.2
    volumes:
      - "./docker/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb

  iperf:
    restart: always
    build: ./build/iperf-client
    container_name: iperf-client
    command: python iperf.py
    ports:
      - "${IPERF_LISTEN_PORT}:${IPERF_LISTEN_PORT}/udp"
    tty: true
    environment:
      - "IPERF_INTERVAL=${IPERF_INTERVAL}"
      - "SPEEDTEST_HOST_PING=${SPEEDTEST_HOST_PING}"
      - "SPEEDTEST_HOST_IPERF=${SPEEDTEST_HOST_IPERF}"
      - "INFLUXDB_DB=${INFLUXDB_DB}"
      - "INFLUXDB_DB_PORT=${INFLUXDB_DB_PORT}"
      - "INFLUXDB_USERNAME=root"
      - "INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}"
      - "INFLUXDB_HOST=${INFLUXDB_HOST}"
    depends_on:
      - influxdb

